name: Deploy to Fly.io

on:
  push:
    branches:
      - main  # or 'master' or your branch name

jobs:
  deploy:
    name: Deploy to Fly
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy app
        run: fly deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
